spring:
  application:
    name: cloud-storage-in-action
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

gcp:
  project-id: mineral-droplet-479913-m9
  credentials-location: mineral-droplet-479913-m9-f5899e7a58a9.json
  bucket-id: its_capstone_bucket_1